[package]
name = "tcp"
version.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
