[package]
name = "p2p"
version.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
