#!/bin/bash

echo "=== P2P直接通信 vs 服务器转发测试演示 ==="
echo ""
echo "您的问题：收到的消息都是服务器转发的吗？有没有p2p的？"
echo ""
echo "答案：现在有真正的P2P直接通信了！"
echo ""
echo "请按照以下步骤测试："
echo ""
echo "1. 服务器已启动在 127.0.0.1:8080"
echo ""
echo "2. 开启第一个终端运行:"
echo "   cd /Users/ji.wu/RustroverProjects/learn/src/p2p"
echo "   cargo run --example client"
echo "   输入用户名: alice"
echo ""
echo "3. 开启第二个终端运行:"
echo "   cd /Users/ji.wu/RustroverProjects/learn/src/p2p"
echo "   cargo run --example client"  
echo "   输入用户名: bob"
echo ""
echo "4. 在alice终端测试服务器转发:"
echo "   @bob 这是服务器转发的消息"
echo "   --> bob会看到: [服务器]私聊[alice]: 这是服务器转发的消息"
echo ""
echo "5. 在alice终端建立P2P连接:"
echo "   /p2p bob"
echo "   --> 看到: ✨ 已直接连接到对等节点: bob"
echo ""
echo "6. 在alice终端发送P2P直接消息:"
echo "   /direct bob 这是P2P直接消息！"
echo "   --> bob会看到: [P2P]私聊[alice]: 这是P2P直接消息！"
echo ""
echo "🎯 关键区别："
echo "   [服务器] = 通过服务器转发"
echo "   [P2P] = 客户端直接连接，不经过服务器"
echo ""
echo "现在您的系统同时支持两种通信方式！"