#!/bin/bash

echo "🧪 P2P连接测试演示"
echo "=================="
echo ""
echo "步骤说明："
echo "1. 服务器已在 127.0.0.1:8080 启动"
echo "2. 现在需要手动测试客户端连接"
echo ""
echo "请按以下步骤操作："
echo ""
echo "📋 终端1 - 启动客户端alice："
echo "   cd /Users/ji.wu/RustroverProjects/learn/src/p2p"
echo "   echo 'alice' | cargo run --example client"
echo ""
echo "📋 终端2 - 启动客户端bob："
echo "   cd /Users/ji.wu/RustroverProjects/learn/src/p2p"  
echo "   echo 'bob' | cargo run --example client"
echo ""
echo "📋 在alice终端测试P2P连接："
echo "   /p2p bob"
echo ""
echo "🔍 观察点："
echo "- 服务器是否显示正确的监听端口"
echo "- 客户端是否收到对等节点列表"
echo "- P2P连接是否成功建立"
echo ""
echo "如果连接失败，可能的原因："
echo "1. 监听端口为0（客户端没有监听）"
echo "2. 对等节点列表没有正确接收"
echo "3. 网络连接问题"